### model
model_name_or_path: /mnt/home/user28/llms/Qwen2.5-7B-Instruct
trust_remote_code: true

### method
do_train: true
do_eval: true
predict_with_generate: true

### dataset
dataset: alfworld_metaplan_train.json, sciworld_metaplan_train.json
eval_dataset: metaplan_eval.json
template: qwen
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
mix_strategy: interleave_over
preprocessing_num_workers: 16
dataloader_num_workers: 2

### output
output_dir: /mnt/home/user28/llms/Qwen2.5-7B-Instruct-checkpoints/MAML_gen_plan
logging_steps: 5
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 4  # total batch size = support set size + query set size
dataloader_drop_last: true
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
